### ISSUE TITLE
ダウンロードした際のradixファイルの位置が正しくない問題

### ISSUE THREAD

**Issue by Suree33** [7304sk/RADIX#1]
このGitHubからテンプレートを取得しようとする際、現状では

- package
  - css
    - style.css
  - js
    - index.js
  - HINA.html
- radix.css
- radix.js
…

のようなディレクトリ構造になっていますが、実際にこのフレームワークを使用しようとした場合、

- css
  - radix.css
  - style.css
- js
  - radix.js
  - index.js
- HINA.html もしくは index.html

のようになるほうが使いやすいように思います。

GitHubではReleases機能を使うことで、開発時のディレクトリ構造等とは別に、バージョン番号付きでダウンロード用のファイルを設定することができます。こちらを使って理想的なディレクトリ構造のzipファイルをダウンロードできるようにすることで、上記の問題を解決できると思います。

[リポジトリのリリースを管理する - GitHub Docs](https://docs.github.com/ja/repositories/releasing-projects-on-github/managing-releases-in-a-repository)
[GitHubのリリース機能を使う - Qiita](https://qiita.com/todogzm/items/db9f5f2cedf976379f84)

**Comment by 7304sk** [comment]
Issue ありがとうございます。ご紹介いただいた release 機能を使って、不具合を修正した v3.1.3 をリリースしてみました。

**Comment by Suree33** [comment]
ありがとうございます！最高です！
